TEST_CASE_DURATION_SECONDS = 10 * 60
TIME_BETWEEN_TESTS_TEMPERATURE_CHECK_SECONDS = 5 * 60
LOW_VOLTAGE_VALUE = 20
LOW_VOLTAGE_VALUE_TEST_DURATION_SECONDS = 60

VOLTAGE_ACCURACY_NO_LOAD_TEST_DURATION_SECONDS = 60
TEST_RUNTHROUGH_TEMPERATURE_BYPASS_C = 60.0

SHORT_TEST_DURATION_SECONDS = 3

# Pulse/sequence timing
INTERVAL_MSEC = {1: 100, 2: 200}  # Default to 100 ms interval
NUM_MODULES = (1, 2)

# Default safety / logging timing parameters
# Temperature shutoff thresholds
CONSOLE_SHUTOFF_TEMP_C_DEFAULT = 70.0
TX_SHUTOFF_TEMP_C_DEFAULT = 75.0
AMBIENT_SHUTOFF_TEMP_C_DEFAULT = 75.0

# Voltage deviation limits
VOLTAGE_DEVIATION_ABSOLUTE_VALUE_LIMIT = 2.0
VOLTAGE_DEVIATION_PERCENTAGE_LIMIT = 10.0

# Temperature monitoring intervals
TEMPERATURE_CHECK_INTERVAL_DEFAULT = 1.0
TEMPERATURE_LOG_INTERVAL_DEFAULT = 1.0

MAX_OPERATION_RETRIES = 3
RETRY_DELAY_SECONDS = 1.0